# duplicate detection — LLM score (0–100 scale)
SIMILARITY_THRESHOLD = 70

# runbook execution — vector cosine similarity (0–1 scale)
SOP_SIMILARITY_THRESHOLD = 0.40
RCA_SIMILARITY_THRESHOLD= 0.60

# RCA Threshhold
KB_SIMILARITY_THRESHOLD = 0.48


# vector similarity (0–1)
HISTORICAL_VECTOR_THRESHOLD = 0.60

# LLM rerank score (0–100)
HISTORICAL_LLM_THRESHOLD = 60


# SMART ESCALATION THRESHOLDS
ESC_HIGH_THRESHOLD   = 88
ESC_MEDIUM_THRESHOLD = 60
HITL_AUTO_BOOST_COUNT = 5
HITL_BOOST_AMOUNT = 15